case_study: ctest

scenarios:
  - test

likelihood_landscapes:
  run: True
  n_grid_points: 100
  n_vector_points: 50
  std_dev: 2.0
  conda_env: hmt

pymob_infer:
  cores: 1
  backend: numpyro
  conda_env: hmt
  jax_x64: True

report:
  compile: True